require('plugins.other')
require("plugins.mason")
require("plugins.lspconfig")
require("plugins.nvim-cmp")
require("plugins.nvim-tree")
require('plugins.alpha-nvim')
require('plugins.comment')
require('plugins.bufferline')
require('plugins.autopairs')
require("plugins.treesitter")
require('plugins.lspsaga')
require('plugins.toggleterm')
require('plugins.galaxyline')
require('plugins.dressing')

require('plugins.nui')
require('plugins.luasnip')
require('plugins.copilot')
